### ISSUE TITLE
[v1.3] eth_newFilter incompatibility with eth

### ISSUE THREAD

**Issue by gpBlockchain** [nervosnetwork/godwoken#1025]
### Env
url:https://godwoken-alphanet-v1.ckbapp.dev

### incompatibility case 

- [x] The second call `eth_getFilterChanges` should not have the data from the last call 
```
       it("invoke eth_getFilterChanges 2 times, second logs length must be 0 ", async () => {
            const filterId = await ethers.provider.send("eth_newFilter", [{}]);

            await sendTxToAddBlockNum(3)
            let logs = await ethers.provider.send("eth_getFilterChanges", [filterId]);
            checkLogsIsSort(logs)
            logs = await ethers.provider.send("eth_getFilterChanges", [filterId]);
            expect(logs.toString()).to.be.equal('')
        })
```
- [x] filter : 'fromBlock': 'pending' ,should return invalid from and to block combination: from > to
```
guopenglin@192 axon % curl --location --request POST 'localhost:8545/' \
--header 'Content-Type: application/json' \
--data-raw '{
        "jsonrpc":"2.0",
        "method":"eth_newFilter",
        "params":[
                {
                        "fromBlock":"pending"
                }
        ],
        "id":73
}'
{"jsonrpc":"2.0","id":73,"error":{"code":-32000,"message":"invalid from and to block combination: from \u003e to"}}
guopenglin@192 axon % 
guopenglin@192 axon % 
guopenglin@192 axon % 
guopenglin@192 axon % curl --location --request POST 'https://godwoken-alphanet-v1.ckbapp.dev' \
--header 'Content-Type: application/json' \
--data-raw '{
        "jsonrpc":"2.0",
        "method":"eth_newFilter",
        "params":[
                {
                        "fromBlock":"pending"
                }
        ],
        "id":73
}'
{"jsonrpc":"2.0","id":73,"result":"0x046ed6136470c6ee84f9099feab6f25d"}%        
```
- [ ] filter : fromBlock = eth_blockNumber()+1000 ,should filter log.number >= eth_blockNumber()+1000

- [ ] filter : toBlock = earliest ,should return error msg 
```
guopenglin@192 axon % curl --location --request POST 'https://godwoken-alphanet-v1.ckbapp.dev' \
--header 'Content-Type: application/json' \
--data-raw '{
        "jsonrpc":"2.0",
        "method":"eth_newFilter",
        "params":[
                {
                        "toBlock":"earliest"
                }
        ],
        "id":73
}'
{"jsonrpc":"2.0","id":73,"result":"0x8030aae6fbb589c1a4cd7475fa5d4a64"}%        guopenglin@192 axon % curl --location --request POST 'http://127.0.0.1:8545' \
--header 'Content-Type: application/json' \
--data-raw '{
        "jsonrpc":"2.0",
        "method":"eth_newFilter",
        "params":[
                {
                        "toBlock":"earliest"
                }
        ],
        "id":73
}'
{"jsonrpc":"2.0","id":73,"error":{"code":-32000,"message":"invalid from and to block combination: from \u003e to"}}
```
- [ ] `eth_getFilterChanges` should not return 'Internal error' 
```
jsonRpcRequest: {
  jsonrpc: '2.0',
  method: 'eth_getFilterChanges',
  params: [ '0x9c6fb86fd2fae1a9f1ea691dcab01980' ],
  id: 100
}
jsonRpcResponse: {
  jsonrpc: '2.0',
  id: 100,
  error: { code: -32603, message: 'Internal error' }
}
```
test code 
```
         it("[[A, B], [A, B]].yes,should return logs", async () => {
                //check get filed id success
                expect(filterMsgMap["topic.[[A, B],[A, B]].yes"].error).to.be.equal(undefined)
                expect(filterMsgMap["topic.[[A, B],[A, B]].yes"].logs.length).to.be.not.equal(0)
                await checkLogsGteHeight(filterMsgMap["topic.[[A, B],[A, B]].yes"].logs, blockHeight)
                await checkLogsIsSort(filterMsgMap["topic.[[A, B],[A, B]].yes"].logs)
            })
```
test repo:https://github.com/gpBlockchain/godwoken-tests/blob/issue-test/contracts/test/Issue.js#L7

**Comment by keroro520** [comment]
> * The second call eth_getFilterChanges should not have the data from the last call

Empty logs should be represented as `[]` but not `''`.
The last assertion should be changed to 

```js
expect(logs).to.be.equal([]);
```

And I have created a similar testcase before 😄  https://github.com/nervosnetwork/godwoken-tests/pull/143/files#diff-5a9d016b1531b5de7f83f95c594c036c72e18a10fed58d5897157dce20beebbaR66

**Comment by keroro520** [comment]
> *  filter : 'fromBlock': 'pending' ,should return invalid from and to block combination: from > to
> *  filter : toBlock = earliest ,should return error msg

Your suggestion is a worthy enhancement. Currently, Godwoken-Web3 returns an empty array `[]`, which is okay for users. Let's mark it as a P-Medium enhancement task.

**Comment by keroro520** [comment]
> *  filter : fromBlock = eth_blockNumber()+1000 ,should filter log.number >= eth_blockNumber()+1000
> * eth_getFilterChanges should not return 'Internal error'

I do not quite understand these two cases. Would you like to provide more information？ @gpBlockchain

**Comment by gpBlockchain** [comment]
> > * The second call eth_getFilterChanges should not have the data from the last call
> 
> Empty logs should be represented as `[]` but not `''`. The last assertion should be changed to
> 
> ```js
> expect(logs).to.be.equal([]);
> ```
> 
> And I have created a similar testcase before 😄 https://github.com/nervosnetwork/godwoken-tests/pull/143/files#diff-5a9d016b1531b5de7f83f95c594c036c72e18a10fed58d5897157dce20beebbaR66

[].toString() == ""
<img width="867" alt="image" src="https://user-images.githubusercontent.com/32102187/180707263-ee93ee7c-50ea-491f-8b2b-9209d78fe421.png">
i will mod message that not use toString expected

**Comment by gpBlockchain** [comment]
> I do not quite understand these two cases. Would you like to provide more information

If the current block height < fromBlock, send `eth_getFilterChanges` should return empty ,but now will return logs that logs.height < fromBlock

**Comment by gpBlockchain** [comment]
> > I do not quite understand these two cases. Would you like to provide more information
> 
> 
- filter : 'fromBlock': 'pending' ,should return invalid from and to block combination: from > to

If the current block height < fromBlock, send `eth_getFilterChanges` should return empty ,but now will return logs that logs.height < fromBlock

- eth_getFilterChanges should not return 'Internal error'
return   'Internal error' when Filters are complex that contains multiple topic conditions ,reproducible with this use case
https://github.com/gpBlockchain/godwoken-tests/blob/issue-test/contracts/test/Issue.js#L78-L126
#### solidity code 
```
function testLog4(uint256 logCount) public {
        for(uint256 i=0;i<logCount;i++){
            log4(
                bytes32(0x0000000000000000000000000000000000000000000000000000000000000000),
                bytes32(0x0000000000000000000000000000000000000000000000000000000000000001),
                bytes32(0x0000000000000000000000000000000000000000000000000000000000000002),
                bytes32(0x0000000000000000000000000000000000000000000000000000000000000003),
                bytes32(0x0000000000000000000000000000000000000000000000000000000000000004)
            );
        }
    }
```
constant
```
let topic0="0x0000000000000000000000000000000000000000000000000000000000000001";
let topic1="0x0000000000000000000000000000000000000000000000000000000000000002";
let topic2="0x0000000000000000000000000000000000000000000000000000000000000003";
let topic3="0x0000000000000000000000000000000000000000000000000000000000000004";
```
#### step
1. invoke deploy contract that contains `testLog4` method 
2. send `eth_newFillter` that fillter is `{"topics": [[topic0, topic2,topic3], [null, topic2],[topic1]] }`
3. invoke  `testLog4` method 20 times
4. send eth_getFilterChanges 
#### result 
4. eth_getFilterChanges return 'Internal error' expected return log message

**Comment by keroro520** [comment]
> 

`"topics": [[topic0, topic2,topic3], [null, topic2],[topic1]]` is invalid as subtopic cannot be `null`.

**Comment by keroro520** [comment]
> > 
> 
> `"topics": [[topic0, topic2,topic3], [null, topic2],[topic1]]` is invalid as subtopic cannot be `null`.

It should throw InvalidFilterTopic when creating a filter, but now InternalError. It is a bug.

**Comment by classicalliu** [comment]
1.  It's passed on testnet & alphanet
2. It returns `{"jsonrpc":"2.0","id":73,"result":"0x1"}` on my `http://localhost:8545`(hardhat node)
3. This test case will also failed in hardhat, from hardhat's [code](https://github.com/NomicFoundation/hardhat/blob/8da0be1874/packages/hardhat-core/src/internal/hardhat-network/provider/node.ts#L2445) , when `fromBlock > latestBlockNumber`， `fromBlock` will set to `latestBlockNumber`
4. It returns `{"jsonrpc":"2.0","id":73,"result":"0x2"}` on hardhat node
5. It will be fixed by https://github.com/godwokenrises/godwoken/pull/1024

**Comment by sunchengzhu** [comment]
3. I use `eth_newFilter` in alchemy's goerli network, which supports the use of `fromBlock` greater than the current block height, and the filter will take effect when the block height reaches `fromBlock`.
And the same scenario on Godwoken alphanet v1.13.0-rc1 `eth_getFilterChange` returns `{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"header not found"}}`.

**Comment by sunchengzhu** [comment]
I found that the first call of `eth_getFilterChanges` is different in hardhat and geth. Is godwoken consistent with hardhat or geth?
 1. Use `"fromBlock": "0x1"` to create a filter
2. Pass in the created filter_id to call `eth_getFilterChanges`
3. Hardhat will return all log arrays from `0x1` to the current block matching, while geth will only return`[]`
![image](https://user-images.githubusercontent.com/36075573/230632828-451cd194-e684-4ceb-b62e-82c8696a5bb0.png)

**Comment by classicalliu** [comment]
> 3. I use `eth_newFilter` in alchemy's goerli network, which supports the use of `fromBlock` greater than the current block height, and the filter will take effect when the block height reaches `fromBlock`.
>    And the same scenario on Godwoken alphanet v1.13.0-rc1 `eth_getFilterChange` returns `{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"header not found"}}`.


- https://github.com/godwokenrises/godwoken/pull/1049

Performs like Geth now

**Comment by classicalliu** [comment]
> I found that the first call of `eth_getFilterChanges` is different in hardhat and geth. Is godwoken consistent with hardhat or geth?
> 
> 1. Use `"fromBlock": "0x1"` to create a filter
> 2. Pass in the created filter_id to call `eth_getFilterChanges`
> 3. Hardhat will return all log arrays from `0x1` to the current block matching, while geth will only return`[]`
>    ![image](https://user-images.githubusercontent.com/36075573/230632828-451cd194-e684-4ceb-b62e-82c8696a5bb0.png)

We can keep the status quo, which performs like Geth now.
