### ISSUE TITLE
[BUG] currently does not support client body read timeout

### ISSUE THREAD

**Issue by chenyukang** [nervosnetwork/godwoken#1054]
From the code:

https://github.com/godwokenrises/godwoken/blob/2d8ad3510fcd528dfbfe76242b9572acdcf25084/crates/rpc-server/src/server.rs#L51

Seems `godwoken` also has a similar issue with `ckb`, https://github.com/nervosnetwork/ckb/issues/3880

I didn't verify it on `godwoken`, but from the code the `rpc` does not has a limit for a request, you can verify it with `curl`:

```console
curl --location 'http://127.0.0.1:3000/rpc' \
-H 'content-length: 100' \
--header 'Content-Type: application/json' \
--data-raw '   {
        "id": 42,
        "jsonrpc": "2.0",
        "method": "@ping",
        "params": [
        ]
   }'

```

An possible fix is to add a `timeout` middleware: https://github.com/chenyukang/jsonrpc-utils/blob/810f6a36eec3ce5be8673c11311bf1dcc506c3f9/examples/server-timeout.rs#L39

**Comment by blckngm** [comment]
Godwoken rpc is usually proxied by web3 / nginx etc., not exposed directly.

But adding a client body size limit / timeout is pretty easy, so I will add it just in case.

**Comment by blckngm** [comment]
@chenyukang Just use TimeoutLayer from tower-http, no need for `ServiceBuilder` and `HandleErrorLayer`.

**Comment by chenyukang** [comment]
> @chenyukang Just use TimeoutLayer from tower-http, no need for `ServiceBuilder` and `HandleErrorLayer`.

Got it, thanks.
