### ISSUE TITLE
godwoken-web3-prebuilds & godwoken-web3-indexer-prebuilds  failed to start

### ISSUE THREAD

**Issue by guomaoqiu** [nervosnetwork/godwoken#1082]
When the godwoken-web3-prebuilds & godwoken-web3-indexer-prebuilds  started, the following problems occur. Can you help to troubleshoot the cause?
![image](https://github.com/godwokenrises/godwoken/assets/9714859/4e2d86ef-f5bc-4916-a2d2-7e1a8fceb179)

**Comment by blckngm** [comment]
Seems that they cannot connect to the postgres database. Can you check whether the database is running and the connection url is correct?

**Comment by guomaoqiu** [comment]
Thank you for your help with the investigation!
