### ISSUE TITLE
[BUG] eth_getCode returns no data of successfully deployed contract

### ISSUE THREAD

**Issue by maciej-kozuszek** [nervosnetwork/godwoken#1086]
**Version**
- Godwoken Testnet v1

 **Describe the bug**
After successfully deploying contract [deploy transaction](https://v1.testnet.gwscan.com/tx/0xb507f21e236f0c066c02206ea1853de7ff8fa35578b62eda19b79f7cfa39f950) the `eth_getCode` returns empty data, also calls on contract methods fails with message `failure` and verifying contracts returns error that there is no contract at address visible in deployed transaction.

**To Reproduce**

Send to godwoken testnet rpc node (https://godwoken-testnet-v1.ckbapp.dev) message:

```json
{
  "method": "eth_getTransactionReceipt",
  "params": [
    "0xb507f21e236f0c066c02206ea1853de7ff8fa35578b62eda19b79f7cfa39f950"
  ],
  "id": 48,
  "jsonrpc": "2.0"
}
```
which should return `"contractAddress": "0x3d22880a87732afc0a40dc9ace540525f92e8bec"`
now call
```json
{
  "method": "eth_getCode",
  "params": [
    "0x3d22880a87732afc0a40dc9ace540525f92e8bec",
    "latest"
  ],
  "id": 48,
  "jsonrpc": "2.0"
}
```
and returned code of deployed contract is empty `"result": "0x"`

**Expected behavior**

Result of last step should give byte code visible in [deploy transaction](https://v1.testnet.gwscan.com/tx/0xb507f21e236f0c066c02206ea1853de7ff8fa35578b62eda19b79f7cfa39f950)

## **Additional context**
Tested on block 3,525,813 and before (contract was deployed on block 3,525,270)

**Comment by blckngm** [comment]
The input of the deploy transaction doesn't seem right, it stops right away (opcode 0x00) so there's no return data. How did you generate or send the deploy transaction? Maybe you can try a different deployment tool?

**Comment by maciej-kozuszek** [comment]
You are right, I deployed on godwoken compiled contract using `zk-solc` compiler for zkSync which generates different bytecode.
