### ISSUE TITLE
重启服务后日志大量刷 select number 语句

### ISSUE THREAD

**Issue by jiangxianliang007** [nervosnetwork/godwoken#184]
重启 godwoken 服务后，日志会一直刷  select number from blocks 这条sql， 看上去它是从第一个块开始查询直到最新的块;
```
SELECT number FROM blocks = 1
SELECT number FROM blocks ....
SELECT number FROM blocks = 5282
```
这样运行的时间很久，产生的区块数量很多时（10W+、100W+），升级重启服务，是不是会存在瞬间大量 select 查询使后端的数据库压力过大； 
![image](https://user-images.githubusercontent.com/24754263/118458134-0168f880-b72d-11eb-90ec-344d06ec0b78.png)

**Comment by jjyr** [comment]
Fixed in new version
