### ISSUE TITLE
L2交易打包上链图 时序是不是画反了？

### ISSUE THREAD

**Issue by PandaTea** [nervosnetwork/godwoken#237]
https://github.com/nervosnetwork/godwoken/tree/master/docs/life_of_a_godwoken_transaction.md

![image](https://user-images.githubusercontent.com/29042336/124870761-c5983400-dff5-11eb-8de0-a7ed48b823ca.png)

这张图讲了 L2的交易 是如何被打包 并发到L1上的
右边应该是汇总交易 并打包block，左边是 确认区块。
要不是时序箭头画反了，要不然是要把整个图镜像一下

**Comment by jjyr** [comment]
画的人的意图应该是箭头代表着左边是更旧的 block，右边是更新的 block。

**Comment by PandaTea** [comment]
> 画的人的意图应该是箭头代表着左边是更旧的 block，右边是更新的 block。

了解了，所以这图没有时序。是一个瞬间的快照。
![image](https://user-images.githubusercontent.com/29042336/125039920-9e129b80-e0c9-11eb-91f3-7c8fea510e86.png)

**Comment by Rbchi** [comment]
An Ethereum app can be used not only via Ethereum wallets such as MetaMask, but also Tron, EOS, BTC or other wallets.

在Polyjuice 注意事项中的这一句，我有个疑问是 Polyjuice 也能够兼容  Unipass 吗？

**Comment by jjyr** [comment]
If unipass provides wallet feature or supports export pk, we can use it to sign txs then.
