### ISSUE TITLE
About "Known Caveats Of Polyjuice"

### ISSUE THREAD

**Issue by Rbchi** [nervosnetwork/godwoken#258]
1.About the path of `pETH`
Today if I would like port 1 ETH into pETH. What does the path look like?
ETH -- force bridge --> ckETH -- change type script of ckETH --> pETH? Is it correct?

2.As usually,does a polyjuice chain represent a dApp as polkadot (Each parachain is backed by a dApp)? Or our rollup would like "Optimism " that all the dApp live on single  polyhuice chain

3.How do the different polyjuice chain provide the feature of IO 2.0? E.g. how does asset bridge from EVM compatible chain to Diem(Move) compatible chain ?

4.What does the Godwoken address look like ? Will an ETH native address could be converted to Godwoken address automatically by script? And what should our users do for the address transformation?

5.Will we have a demo to teach ppl how to move a Uniswap or other general and popular DeFi dApps to Nervos ?

**Comment by jjyr** [comment]
1. ETH -- force bridge --> ckETH(sUDT) -- deposit ckETH(sUDT) --> pETH(polyjuice), the sUDT that used by ckETH must can be recognized by Godwoken.
2. We can deploy many Godwoken rollup instances on CKB, and many Polyjuice chains on the Godwoken rollup. But in practice I think we should focus on single polyjuice chain and all the dApp lived on the chain.
3. We haven't support this feature in the current version.
4. We provide a web3 provider to convert ETH address to Godwoken address, so a typical user shouldn't care about the Godwoken address.
5. I think it is a good idea, but currently, we are still focusing on the development of the Godwoken. We may release some demos when we have time to do.

**Comment by Rbchi** [comment]
First of all,thanks for your replying.It is helpful
1. will the type script of ckETH got any change after depositing ?
2. Yeah it makes sense.
3.Got it,no worries.Diem is still at an early age.
4. Wow,it let me feel more confident for Polyjuice&Godwoken's user experience.
5.Of course,take your time. My thought is that when we could have some demo videos for migrating famous DeFi dApps,community devs could use the example to run their own business.Here I list some dApps deserving to have on Godwoken.(Surely it may not the best answer but be free to have a look)
- AMM:Uniswap(the most popular AMM),Curve(stablecoin swap) and 1inch(aggregator)
- Lending : Compound \Aave \Maker
- Synthetic asset : Synthetix (their staking reward contract is also the one of most important contracts for liquidity mining.)
- Yield Aggregator : YFI
-Perpetual contract : Perp

**Comment by Rbchi** [comment]
btw,could we add your network to chainlist which is a list for EVM compatible chain.Users can use the information to connect their wallets and Web3 middleware providers to the appropriate Chain ID and Network ID to connect to the correct chain.
https://chainlist.org/

**Comment by jjyr** [comment]
Done
