### ISSUE TITLE
[QUESTION] Is there "Deposit fee" for depositing to Godwoken?

### ISSUE THREAD

**Issue by Kuzirashi** [nervosnetwork/godwoken#374]
If I send transaction to deposit from Nervos Layer 1 to Godwoken do I pay any fee?

Is my calculation correct that you have to pay:

1. Layer 1 transaction fee for depositing (eg. 0.001 CKB)

Is it the only fee or there's more?

Thank you for answer.

**Comment by jjyr** [comment]
Yes, the sequencer do not charge any fee for deposit, but in the future version we may adjust this mechanism.
