### ISSUE TITLE
What happens to Cells locked with Deposit Lock with less than 400 CKB?

### ISSUE THREAD

**Issue by e00dan** [nervosnetwork/godwoken#574]
What happens to Cells locked with Deposit Lock with less than 400 CKB?

eg. someone sends 200 CKB to Godwoken Deposit Address. Godwoken isn't going to collect this deposit. I guess the funds are stuck between Layer 1 and Layer 2. Can user unlock his funds?

**Comment by jjyr** [comment]
In Yokai bridge UI, user can cancel their pending deposits by sending a ckb tx.

**Comment by Flouse** [comment]
## Rationale

> owner_lock_hash and cancel_timeout in `DepositLockArgs` provide a way to redeem the token in the case Godwoken ignores this request(e.g., when the network becomes bloated). cancel_timeout specifies a timeout parameter in CKB's [since](https://github.com/nervosnetwork/rfcs/blob/master/rfcs/0017-tx-valid-since/0017-tx-valid-since.md) format. When the timeout has reached, the user can create another request to cancel the deposit action, and redeem his/her tokens for other use. owner_lock_hash is used to provide the token owner's identity in case of a cancel deposit action.

See: https://github.com/nervosnetwork/godwoken/blob/master/docs/life_of_a_godwoken_transaction.md#deposit
