### ISSUE TITLE
[error] thread 'main' panicked at 'Ahead-of-time compile: InvalidInstruction(82225071)'

### ISSUE THREAD

**Issue by xcshuan** [nervosnetwork/godwoken#600]
I modified Godwoken's code( [commit-e99d58c](https://github.com/xcshuan/godwoken/commit/e99d58c1d53e8d893ff85851bfe576e2a0171c1a) ) for test, added a new method in rpc-server/registry.rs, compiled it into binary, and tested it with godwoken-kicker.
However, when I run `make start` in godwoken-kicker, it throws the error below.
```
docker-godwoken-1    | 2022-02-24T13:03:17.421489Z  INFO gw_block_producer::runner: Runtime threads: 8. (set environment 'SMOL_THREADS' to tune this value)
docker-godwoken-1    | 2022-02-24T13:03:17.759893Z  INFO gw_db::migrate: Init db version: 20211229181750
docker-godwoken-1    | 2022-02-24T13:03:17.789257Z  INFO gw_generator::backend_manage: Compile AotCode with VMVersion::V0
docker-godwoken-1    | 2022-02-24T13:03:17.794599Z  INFO gw_generator::backend_manage: Compile AotCode with VMVersion::V1
docker-godwoken-1    | 2022-02-24T13:03:17.800579Z  INFO gw_generator::backend_manage: Compile AotCode with VMVersion::V0
docker-godwoken-1    | 2022-02-24T13:03:17.806267Z  INFO gw_generator::backend_manage: Compile AotCode with VMVersion::V1
docker-godwoken-1    | 2022-02-24T13:03:17.811963Z  INFO gw_generator::backend_manage: Compile AotCode with VMVersion::V0
docker-godwoken-1    | thread 'main' panicked at 'Ahead-of-time compile: InvalidInstruction(82225071)', crates/generator/src/backend_manage.rs:67:22
docker-godwoken-1    | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
docker-godwoken-1 exited with code 101
```
I did not modify the configuration of godwoken-kicker, only copied the binary I compiled to the workspace/bin folder

**Comment by Flouse** [comment]
In the latest version([v0.10.1](https://github.com/nervosnetwork/godwoken/releases/tag/v0.10.1
)), the [`aot-vm`](https://github.com/nervosnetwork/ckb-vm#notes-on-different-modes) feature is enabled by default. Please update Polyjuice generator to [v0.8.10-aot](https://github.com/nervosnetwork/godwoken-polyjuice/releases/tag/v0.8.10-aot),
or use the Polyjuice generator in [nervos/godwoken-prebuilds:v0.10.1](https://hub.docker.com/layers/nervos/godwoken-prebuilds/v0.10.1/images/sha256-7b5dea15031a2a512e41e8ec6bbdca656c4d5b231268153db7d12ddfd1baf6cb?context=explore) .
> `/scripts/godwoken-polyjuice/generator` is now equals to `/scripts/godwoken-polyjuice/generator.aot`

**Comment by xcshuan** [comment]
Modify the Makefile and use the generator in aot mode, the problem is solved.
