### ISSUE TITLE
fix(gw-tools generate-config): set `producer.account_id` to the real one

### ISSUE THREAD

**Issue by Flouse** [nervosnetwork/godwoken#616]
In the current version, block_producer.account_id is default to 0.
We should set `producer.account_id` to the real one related to [block_producer.wallet_config].

In Godwoken v1, block producer should be an ETH EOA.

Related PR
- https://github.com/RetricSu/godwoken-kicker/pull/188

**Comment by keroro520** [comment]
- https://github.com/nervosnetwork/godwoken/pull/634

**Comment by Flouse** [comment]
- #634 was just a temporary solution.

IMO, it is better to remove `account_id` in [block_producer] config.

And we could get the block_producer.account_id through this process:
```
producer_private_key -> eth_address -> account_script (ETH EOA account script) 
-> account_script_hash -> account_id
```

see `build_eth_l2_script` function:
https://github.com/nervosnetwork/godwoken-polyjuice/blob/compatibility-breaking-changes/polyjuice-tests/src/helper.rs#L663-L672

**Comment by Flouse** [comment]
> IMO, it is better to remove `account_id` in [block_producer] config.

`account_id` has been removed from [block_producer] config.
> https://github.com/nervosnetwork/godwoken/commit/bc8884aa768e3662fc70ada03d69a09012af3c19#diff-7cabbf516f45eaeed2dfa75063ad1da979b020f190a3bf6cdd4adaf23fe6826eL159
