### ISSUE TITLE
Remove mandatory eip-155 txs for multi-chain factories deployment

### ISSUE THREAD

**Issue by xcshuan** [nervosnetwork/godwoken#775]
[eip-2470](https://eips.ethereum.org/EIPS/eip-2470), [eip-1820](https://eips.ethereum.org/EIPS/eip-1820), [eip-4337](https://eips.ethereum.org/EIPS/eip-4337), [Gnosis factories](https://github.com/5afe/safe-factories), other smart contract wallets and some defi protocol (https://github.com/celo-org/celo-blockchain/issues/1734), all seem to rely on support for non-eip-155 transactions, especially eip-2470 and eip-1820, which are constructed rather than signed transactions, so no one knows the private key behind the transaction.

The strategy adopted by Godwoken now is to enforce the use of eip-155 transactions, which makes the above contracts difficult or impossible to deploy on Godwoken, which may affect the multi-chain deployment of some protocols.

Avax and celo used this strategy but changed it later due to various incompatibilities. https://github.com/celo-org/celo-proposals/blob/master/CIPs/cip-0050.md

**Comment by e00dan** [comment]
For Gnosis Safe this is non-issue, because Gnosis Safe is already deployed deterministically to our testnet and it has factory that supports EIP155: https://github.com/safe-global/safe-singleton-factory

https://github.com/safe-global/safe-singleton-factory/blob/main/artifacts/71401/deployment.json
