### ISSUE TITLE
Transaction fails with 100% gas consuming

### ISSUE THREAD

**Issue by Roger-RumbleFish** [nervosnetwork/godwoken#814]
[IBAMM.zip](https://github.com/godwokenrises/godwoken/files/9809676/IBAMM.zip)
to reproduce the problem use the ABI with contract -> 0xD839F4468A47Ac17321c28669029d069AB73F535

call method -> liquidateBorrow
parameters -> 0xc207a5dc49771a71367bd3a97fe58aaf9c5dfdae, 3131255, 0xec2bf7ec6afcec1594baf4f33736573d0a12c25e
result: On staticCall method pass but on normal it hang and consume all the gas

**Comment by magicalne** [comment]
I just tried to reproduce in my local environment(by loading binaries from mainnet). Here is what I see.
I can confirm the transaction failed, but __100% gas consuming_ is not confirmed. Gas used ~474_000.

The tx is failed in a very weird way. It looks like [this contract](https://v1.gwscan.com/account/0x3d8714a8e553fb872ac3790c49e9480ab1d31342) cannot be found. I'm still working on it. It's more like a bad way to produce in my local env.

Meantime, can you please share a minimum repo with us including solidity files? That will help a lot. @Roger-RumbleFish

---
### eth_call

```sh
curl --location --request POST 'https://v1.mainnet.godwoken.io/rpc' \
--header 'Content-Type: application/json' \
--data-raw '{
        "jsonrpc":"2.0",
        "method":"eth_call",
        "params":[
{"from": "0xc7035d9319654fae4a0abe9a88121b9d9c36900f", "to": "0xd839f4468a47ac17321c28669029d069ab73f535", "gas": "0x989680", "gasPrice": "0x246139ca8000", "data": "0xf5e3c462000000000000000000000000c207a5dc49771a71367bd3a97fe58aaf9c5dfdae00000000000000000000000000000000000000000000000000000000000003e8000000000000000000000000ec2bf7ec6afcec1594baf4f33736573d0a12c25e", "value": "0x0"}, "latest"],
        "id":1
}'
```
return data:
```json
{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"execution reverted: ReentrancyGuard: reentrant call","data":"0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000001f5265656e7472616e637947756172643a207265656e7472616e742063616c6c00"}}
```

**Comment by Flouse** [comment]
Hi, @Roger-RumbleFish 
The max cycles of a layer2 transaction has been adjusted up to 500M since mainnet_v1_block#233000.
The issue should now be resolved. Can you confirm this?

## References
- fork(consensus): Increase l2 tx max cycles from 150M to 500M 
   https://github.com/godwokenrises/godwoken/pull/852
- https://github.com/godwokenrises/godwoken-info/pull/78

**Comment by Flouse** [comment]
Please feel free to re-open this issue if you still encounter this kind of tx.
