### ISSUE TITLE
Zero-padding hex quantity causes hardhat to freak out

### ISSUE THREAD

**Issue by kowalski** [nervosnetwork/godwoken#818]
Hi,

I have a problem when trying to use hardhat with godwoken mainnet.
I've performed `eth_getTransactionByHash` on transaction `0x101d54bddd747628d62e289506db5461dd68a3c3f910743760e81dc0e9cce6c1` and got the following result.

```
  value: {
    hash: '0x101d54bddd747628d62e289506db5461dd68a3c3f910743760e81dc0e9cce6c1',
    blockHash: '0x68ca20e68228027ceb2b61f3cff26cf277a21f63a0a103c0a3981143c38df65b',
    blockNumber: '0x2db6f',
    transactionIndex: '0x5',
    from: '0xb0d0fc380a13f0179974c447f36d10bd00560805',
    to: '0xc806a37164860913fbff8d013986229724d6c418',
    gas: '0x121e4',
    gasPrice: '0x246139ca8000',
    input: '0x7898e0c20000000000000000000000000000000000000000000000000000000000000060000000000000000000000000000000000000000000000000000000064f429b6700000000000000000000000000000000000000000000000000000000634fb99e0000000000000000000000000000000000000000000000000000000000000007424e422f55534400000000000000000000000000000000000000000000000000',
    nonce: '0x5559',
    value: '0x0',
    v: '0x0',
    r: '0x6a6a50e50e270fcce5a51b368cdbe7fa58325bd5a71e93052adbe2e31cbda360',
    s: '0x0f95565b28d42f0785bc5bb358223292232e749da2b3aece843c1c4e372bf47c'
  }
```

When hardhat parses this it validates each field. I'm getting a following error 
```
  Errors: Invalid value "0x0f95565b28d42f0785bc5bb358223292232e749da2b3aece843c1c4e372bf47c" supplied to : RpcTransaction | null/s: QUANTITY
```
which, to be fair, they could have done a better job explaining what is going on.

When diving a bit deeper to the code I found that this value is being passed through this function https://github.com/NomicFoundation/hardhat/blob/5c31db69a0981440c17dc7d24f8deeeaf5bc8f32/packages/hardhat-core/src/internal/core/jsonrpc/types/base-types.ts#L188 and it uses the following regexp:

```
function isRpcQuantityString(u: unknown): u is string {
  return (
    typeof u === "string" &&
    u.match(/^0x(?:0|(?:[1-9a-fA-F][0-9a-fA-F]*))$/) !== null
  );
}
```

Again, unless you are more adept in reading regexp than I am, it still isn't evident what is going on.
So I run the `node` console and tried to following:

```
> u='0x0f95565b28d42f0785bc5bb358223292232e749da2b3aece843c1c4e372bf47c'
'0x0f95565b28d42f0785bc5bb358223292232e749da2b3aece843c1c4e372bf47c'
> u.match(/^0x(?:0|(?:[1-9a-fA-F][0-9a-fA-F]*))$/)
null
> u='0xf95565b28d42f0785bc5bb358223292232e749da2b3aece843c1c4e372bf47c'
'0xf95565b28d42f0785bc5bb358223292232e749da2b3aece843c1c4e372bf47c'
> u.match(/^0x(?:0|(?:[1-9a-fA-F][0-9a-fA-F]*))$/)
[
  '0xf95565b28d42f0785bc5bb358223292232e749da2b3aece843c1c4e372bf47c',
  index: 0,
  input: '0xf95565b28d42f0785bc5bb358223292232e749da2b3aece843c1c4e372bf47c',
  groups: undefined
]
```

As you can see changing `0x0f..` to `0xf..` does the trick. I believe that godwoken is wrongly left-padding quantity values with zero, and hardhat parsers really doesn't like it.

It's something you might consider fixing to make it easier to use with commonly used tools.

**Comment by classicalliu** [comment]
Thanks for your report, the bug will be fixed by the following PR:
- https://github.com/godwokenrises/godwoken-web3/pull/560

**Comment by RetricSu** [comment]
@kowalski  hi, we have updated the mainnet with the release including this fixed. can you check if the issue has been resolved?

**Comment by kowalski** [comment]
> @kowalski hi, we have updated the mainnet with the release including this fixed. can you check if the issue has been resolved?

@maciej-kozuszek since you took this over, please check and provide feedback on this ticket

**Comment by maciej-kozuszek** [comment]
Checked this on mainnet - blocks 188651 and 188650 couldn't be indexing through hardhat but now it's working as expected and `eth_getTransactionByHash` for block `0x101d54bddd747628d62e289506db5461dd68a3c3f910743760e81dc0e9cce6c1` returns correct `s` value.
