### ISSUE TITLE
How to debug local Devnet

### ISSUE THREAD

**Issue by songjianyang** [nervosnetwork/godwoken#926]
How to debug local Devnet? Is there a way to load source code using gdb? And break the execution flow of godwoken.

**Comment by jjyr** [comment]
Godwoken is written in rust, and you can use rust debugging tools or IDE to set breakpoints. My recommendation is to write debugging logs in the Godwoken Node.

**Comment by songjianyang** [comment]
If I write debug logs, does that mean I need to recompile?

**Comment by songjianyang** [comment]
In addition, how do I view the logs printed by the ckb_debug function? I checked ckb and godwoken through kicker and found no relevant logs.

**Comment by jjyr** [comment]
> If I write debug logs, does that mean I need to recompile?

Yes.


> In addition, how do I view the logs printed by the ckb_debug function? I checked ckb and godwoken through kicker and found no relevant logs.

Set environment variable `RUST_LOG=info,gw_generator=debug` in `docker-compose.yml`.

**Comment by songjianyang** [comment]
thanks
