### ISSUE TITLE
[BUG] Failed transaction without reversing.

### ISSUE THREAD

**Issue by alejandroRbit** [nervosnetwork/godwoken#954]
## **Version**
- Godwoken v1 

## **Describe the bug**

The user claims to have made a transaction using YokaiSwap, swapping from Koi Token to CKB Token (50,000 worth of CKB), the transaction has failed and apparently he has lost all the funds involved in the transaction, not just the gas fee. The balance has not reappeared in YokaiSwap or in his wallet.

**Expected behavior**

Lose only the gas fee of the transaction when it fails.

**Screenshots or Logs**

- Wallet: Metamask 
- TXID: https://v1.gwscan.com/tx/0x9e1e4d9e420d60f962ce02407d59976889f636f29c5f15e3f6d496aa193bc113
- L1 ADDRESS: ckb1qj0n46hjl3pe2jwtepcvv5ehf9p6l94qvk9addgmarvfsvvrum6j7qw0ds789k3rwzzeuguhenmd46y6ae0rnmsqlyvelk
- L2 ADDSRESS: 0xCF6C3c72dA2370859e2397CcF6dae89Aee5E39ee

![Screenshot_20230118-235140_Chrome](https://user-images.githubusercontent.com/94946624/213312803-2687791b-217c-4917-923d-111d01b2edf0.jpg)

## **Additional context**
The user has checked the basic things, such as CKB funds in L1.

**Comment by jjyr** [comment]
Hi, I have reviewed the transfer record of the user.

The user transfers his koi token to another address in this tx https://v1.gwscan.com/tx/0x8e688ed8538957bea58b0a6d87c7012e9f60b8487be4095434d4bea14539f3ce

<img width="1239" alt="image" src="https://user-images.githubusercontent.com/1695400/213400851-27095cb9-c080-4b36-9d52-123e14243794.png">

The user's koi Token becomes zero, and the failed tx just after this one.

So it may be the reason why https://v1.gwscan.com/tx/0x9e1e4d9e420d60f962ce02407d59976889f636f29c5f15e3f6d496aa193bc113 is failed.

<img width="1236" alt="image" src="https://user-images.githubusercontent.com/1695400/213401321-1ff038e8-38ee-4294-bd09-8312115de2d0.png">

Can you confirm it with the user?

**Comment by alejandroRbit** [comment]
> Hola, he revisado el registro de transferencia del usuario.
> 
> El usuario transfiere su token koi a otra dirección en este tx https://v1.gwscan.com/tx/0x8e688ed8538957bea58b0a6d87c7012e9f60b8487be4095434d4bea14539f3ce
> 
> <img alt="imagen" width="1239" src="https://user-images.githubusercontent.com/1695400/213400851-27095cb9-c080-4b36-9d52-123e14243794.png">
> 
> El token koi del usuario se convierte en cero, y el tx fallido justo después de este.
> 
> Entonces, puede ser la razón por la cual https://v1.gwscan.com/tx/0x9e1e4d9e420d60f962ce02407d59976889f636f29c5f15e3f6d496aa193bc113 falla.
> 
> <img alt="imagen" width="1236" src="https://user-images.githubusercontent.com/1695400/213401321-1ff038e8-38ee-4294-bd09-8312115de2d0.png">
> 
> ¿Puedes confirmarlo con el usuario?

I asked him and he told me this:

"Okay so i was in my yokaiswap i swap ckb to koi as i was going to farm it with yokai...
It then didn't let me farm it with yokai so i decided to swap it back to ckb and as i was doing that it failed twice and the 2nd time i never saw my koi back in my wallet...

I had the right gas and all so i really don't get why it was failing

Everything was inside my yokaiswap account nothing out of them addresses"

**Comment by Flouse** [comment]
The user has already remembered the [transaction](https://v1.gwscan.com/tx/0x8e688ed8538957bea58b0a6d87c7012e9f60b8487be4095434d4bea14539f3ce) which sent out all KOI.
So, we closed this issue.
It's not a bug of Godwoken.
